#!/bin/bash

echo "in - information about my scripts         ex. [in]"
echo "ll - ls -alF                              ex. [ll]"
echo "la - ls -A                                ex. [la]"
echo "l - ls -CF                                ex. [l]"
echo "t - ls -R                                 ex. [t]"
echo "tl - ls -Rl                               ex. [tl]"
echo ".. - cd ../                               ex. [..]"
echo "... - cd ../../                           ex. [...]"
echo ".... - cd ../../../                       ex. [....]"
echo "..... - cd ../../../../                   ex. [.....]"
echo "cy - copy from file                       ex. [cy fileName]"
echo "pe - paste from file                      ex. [pe fileName]"
echo "pdf - open pdf file                       ex. [pdf file.pdf]"
echo "myupdate - max update                     ex. [myupdate]"
echo "tr - timer                                ex. [tr 5m]"
echo "pin - ping google                         ex. [pin 10 30s]"
echo "c - clear screen                          ex. [c]"
echo "psmem10 - report memory                   ex. [psmem10]"
echo "pscpu10 - report process                  ex. [pscpu10]"
echo "rpass - generate password                 ex. [rpass 8]"
echo "tmp - see temperature in Lublin           ex. [tmp]"
echo "untar - extract from .tar files           ex. [untar file.tar]"
echo "extract - extract archive file            ex. [extract file.rar]"
echo "myip - see my ip address                  ex. [myip]"
echo "m - simple calculator                     ex. [m 1+3-3*4]"
echo "sw - swopwatch                            ex. [sw]"
echo "q - exit terminal                         ex. [q]"
echo "tth - text to html editing from clipboard ex. [tth]"
